### ISSUE TITLE
Update to Ionic v4 beta

### ISSUE THREAD

**Issue by skounis** [skounis/supermodular2#38]
We should start working on updated the codebase in v4 version of Ionic. Let's create a new branch and start working on it.

**Comment by phdpua** [comment]
@skounis 

Hi Stavros!

I finished with task.

Here is the branch https://github.com/appseed-io/supermodular2/tree/feature/issue-38-ionic-4

I managed to update most application parts, but unfortunately not everything.

I want to enumerate them, later Taras can fix them.

1. Responsive main menu. Because Ionic 4 changed the model of using their controls towards WebComponents, it is not possible in easy way to change behavior of component with external css rule. That is why currently main menu is alway hidden by default (mobile mode).
2. Components / Gestures. I didn't managed to find documentation for this functionality.
3. Components / Inputs / Inset Labels
